import crypto from 'crypto'
import { prisma } from '@/lib/prisma'

export function generateShareToken(): string {
  return crypto.randomBytes(32).toString('hex')
}

export async function validateShareToken(token: string) {
  const record = await prisma.toolShareToken.findUnique({
    where: { token },
    include: {
      project: { select: { id: true, name: true } },
    },
  })

  if (!record) return null
  if (record.revokedAt) return null
  if (record.expiresAt && record.expiresAt < new Date()) return null

  return record
}

export async function getActiveShareTokens(projectId: string, toolKey: string) {
  return prisma.toolShareToken.findMany({
    where: {
      projectId,
      toolKey,
      revokedAt: null,
      OR: [
        { expiresAt: null },
        { expiresAt: { gt: new Date() } },
      ],
    },
    orderBy: { createdAt: 'desc' },
  })
}

export async function getReportSettings(): Promise<{
  hideNotesInPublicShare: boolean
  logoUrl?: string
  companyName: string
  reportTitle: string
  footerText: string
}> {
  const setting = await prisma.siteSetting.findUnique({
    where: { key: 'report.punchlist' },
  })

  const defaults = {
    hideNotesInPublicShare: false,
    companyName: 'HawaiiHomeCentral.com',
    reportTitle: 'Punchlist Report',
    footerText: 'Generated by Hawaii Home Central',
  }

  if (!setting) return defaults

  try {
    return { ...defaults, ...JSON.parse(setting.value) }
  } catch {
    return defaults
  }
}
