'use client'

import { useEffect, useState, useMemo } from 'react'
import { useSearchParams } from 'next/navigation'
import { usePunchlistState } from '../usePunchlistState'
import type { PunchlistItem, PunchlistStatus } from '../types'

const STATUS_LABEL: Record<PunchlistStatus, string> = {
  OPEN: 'Open',
  IN_PROGRESS: 'In Progress',
  DONE: 'Done',
}

const STATUS_ORDER: PunchlistStatus[] = ['OPEN', 'IN_PROGRESS', 'DONE']

interface ReportSettings {
  logoUrl?: string
  reportTitle: string
  footerText: string
}

export function PunchlistReport() {
  const searchParams = useSearchParams()
  const includeNotes = searchParams.get('includeNotes') === 'true'
  const includeComments = searchParams.get('includeComments') === 'true'
  const { payload, isLoaded } = usePunchlistState()
  const [settings, setSettings] = useState<ReportSettings>({
    reportTitle: 'Punchlist Report',
    footerText: 'Generated by Hawaii Home Central',
  })

  // Load admin report settings
  useEffect(() => {
    async function load() {
      try {
        const res = await fetch('/api/tools/punchlist/report-settings')
        if (res.ok) {
          const data = await res.json()
          setSettings(data)
        }
      } catch {
        // use defaults
      }
    }
    load()
  }, [])

  // Auto-trigger print when loaded
  useEffect(() => {
    if (isLoaded && payload.items.length > 0) {
      const timeout = setTimeout(() => window.print(), 500)
      return () => clearTimeout(timeout)
    }
  }, [isLoaded, payload.items.length])

  const groupedByStatus = useMemo(() => {
    return STATUS_ORDER.map((status) => ({
      status,
      label: STATUS_LABEL[status],
      items: payload.items.filter((i) => i.status === status),
    })).filter((group) => group.items.length > 0)
  }, [payload.items])

  if (!isLoaded) {
    return (
      <div className="flex items-center justify-center min-h-screen">
        <div className="w-6 h-6 border-2 border-gray-300 border-t-gray-600 rounded-full animate-spin" />
      </div>
    )
  }

  return (
    <>
      {/* Print styles */}
      <style>{`
        @media print {
          body { background: white !important; color: black !important; }
          .no-print { display: none !important; }
          .print-only { display: block !important; }
          .page-break-avoid { page-break-inside: avoid; }
        }
        @media screen {
          .print-only { display: none; }
        }
      `}</style>

      <div className="min-h-screen bg-white text-gray-900 print:bg-white">
        {/* Screen-only toolbar */}
        <div className="no-print bg-basalt text-cream px-6 py-3 flex items-center justify-between">
          <button
            type="button"
            onClick={() => window.history.back()}
            className="text-sm text-cream/60 hover:text-cream transition-colors"
          >
            &larr; Back to Punchlist
          </button>
          <button
            type="button"
            onClick={() => window.print()}
            className="px-4 py-1.5 bg-sandstone text-basalt text-sm font-medium rounded-lg hover:bg-sandstone-light transition-colors"
          >
            Print / Save PDF
          </button>
        </div>

        <div className="max-w-3xl mx-auto px-8 py-10">
          {/* Report header */}
          <div className="flex items-start justify-between mb-8 pb-4 border-b-2 border-gray-200">
            <div>
              {settings.logoUrl && (
                <img src={settings.logoUrl} alt="" className="h-10 mb-3" />
              )}
              <h1 className="text-2xl font-bold text-gray-900">{settings.reportTitle}</h1>
              <p className="text-sm text-gray-500 mt-1">
                Generated {new Date().toLocaleDateString()}
              </p>
            </div>
            <div className="text-right">
              <p className="text-sm text-gray-500">{payload.items.length} total items</p>
            </div>
          </div>

          {/* Notes banner */}
          <div className={`px-4 py-2 rounded-lg text-sm mb-6 ${
            includeNotes
              ? 'bg-green-50 text-green-700 border border-green-200'
              : 'bg-gray-50 text-gray-500 border border-gray-200'
          }`}>
            Notes: {includeNotes ? 'INCLUDED' : 'NOT INCLUDED'}
          </div>

          {/* Items grouped by status */}
          {groupedByStatus.map(({ status, label, items }) => (
            <div key={status} className="mb-8">
              <h2 className="text-lg font-semibold text-gray-800 mb-3 pb-1 border-b border-gray-200">
                {label} ({items.length})
              </h2>
              <div className="space-y-4">
                {items.map((item) => (
                  <ReportItem key={item.id} item={item} includeNotes={includeNotes} includeComments={includeComments} />
                ))}
              </div>
            </div>
          ))}

          {/* Footer */}
          <div className="mt-12 pt-4 border-t border-gray-200 text-center">
            <p className="text-xs text-gray-400">{settings.footerText}</p>
          </div>
        </div>
      </div>
    </>
  )
}

function ReportItem({ item, includeNotes, includeComments }: { item: PunchlistItem; includeNotes: boolean; includeComments: boolean }) {
  return (
    <div className="page-break-avoid border border-gray-200 rounded-lg p-4">
      <div className="flex gap-4">
        {/* Photo thumbnails */}
        {item.photos.length > 0 && (
          <div className="flex gap-1 shrink-0">
            {item.photos.slice(0, 3).map((photo) => (
              <img
                key={photo.id}
                src={photo.thumbnailUrl || photo.url}
                alt=""
                className="w-16 h-16 object-cover rounded"
                loading="lazy"
              />
            ))}
            {item.photos.length > 3 && (
              <div className="w-16 h-16 bg-gray-100 rounded flex items-center justify-center text-xs text-gray-500">
                +{item.photos.length - 3}
              </div>
            )}
          </div>
        )}

        <div className="flex-1 min-w-0">
          <h3 className="font-medium text-gray-900">{item.title}</h3>
          <div className="flex flex-wrap gap-x-4 gap-y-1 mt-1 text-sm text-gray-500">
            <span>Location: {item.location}</span>
            <span>Assignee: {item.assigneeLabel}</span>
            {item.priority && <span>Priority: {item.priority}</span>}
            <span>Status: {STATUS_LABEL[item.status]}</span>
          </div>
          <div className="text-xs text-gray-400 mt-1">
            Created: {new Date(item.createdAt).toLocaleDateString()}
            {item.completedAt && <> &middot; Completed: {new Date(item.completedAt).toLocaleDateString()}</>}
          </div>
          {includeNotes && item.notes && (
            <p className="text-sm text-gray-600 mt-2 italic">{item.notes}</p>
          )}
          {includeComments && item.comments && item.comments.length > 0 && (
            <div className="mt-2 pt-2 border-t border-gray-100">
              <p className="text-xs text-gray-500 font-medium mb-1">Comments ({item.comments.length})</p>
              {item.comments.map((c) => (
                <p key={c.id} className="text-xs text-gray-500 mb-0.5">
                  <span className="font-medium">{c.authorName}</span>
                  {' '}({new Date(c.createdAt).toLocaleDateString()}): {c.text}
                </p>
              ))}
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
