'use client'

import { useState, useEffect, useRef } from 'react'

interface PunchlistReportSettings {
  logoUrl?: string
  reportTitle: string
  footerText: string
  hideNotesInPublicShare: boolean
}

const DEFAULTS: PunchlistReportSettings = {
  reportTitle: 'Punchlist Report',
  footerText: 'Generated by Hawaii Home Central',
  hideNotesInPublicShare: false,
}

export function PunchlistSettingsEditor() {
  const [settings, setSettings] = useState<PunchlistReportSettings>(DEFAULTS)
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [saved, setSaved] = useState(false)
  const [uploading, setUploading] = useState(false)
  const fileRef = useRef<HTMLInputElement>(null)

  useEffect(() => {
    async function load() {
      try {
        const res = await fetch('/api/admin/settings')
        if (!res.ok) return
        const data = await res.json()
        const raw = data['report.punchlist']
        if (raw) {
          setSettings({ ...DEFAULTS, ...JSON.parse(raw) })
        }
      } catch {
        // use defaults
      } finally {
        setLoading(false)
      }
    }
    load()
  }, [])

  async function handleSave() {
    setSaving(true)
    setSaved(false)
    try {
      await fetch('/api/admin/settings', {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          settings: {
            'report.punchlist': JSON.stringify(settings),
          },
        }),
      })
      setSaved(true)
      setTimeout(() => setSaved(false), 3000)
    } catch {
      // silent
    } finally {
      setSaving(false)
    }
  }

  async function handleLogoUpload(file: File) {
    setUploading(true)
    try {
      const formData = new FormData()
      formData.append('file', file)
      const res = await fetch('/api/admin/upload', {
        method: 'POST',
        body: formData,
      })
      if (res.ok) {
        const data = await res.json()
        setSettings((prev) => ({ ...prev, logoUrl: data.url }))
      }
    } catch {
      // silent
    } finally {
      setUploading(false)
    }
  }

  if (loading) {
    return <p className="text-cream/30 text-sm">Loading...</p>
  }

  return (
    <div className="space-y-8 max-w-xl">
      {/* Logo */}
      <div>
        <label className="block text-sm text-cream/70 mb-2">Report Logo</label>
        {settings.logoUrl && (
          <div className="mb-3 flex items-center gap-3">
            <img src={settings.logoUrl} alt="Logo" className="h-10 bg-white/10 rounded p-1" />
            <button
              type="button"
              onClick={() => setSettings((prev) => ({ ...prev, logoUrl: undefined }))}
              className="text-xs text-red-400/60 hover:text-red-400 transition-colors"
            >
              Remove
            </button>
          </div>
        )}
        <button
          type="button"
          onClick={() => fileRef.current?.click()}
          disabled={uploading}
          className="text-sm px-4 py-2 border border-cream/20 rounded-lg text-cream/60 hover:text-cream hover:border-cream/40 transition-colors disabled:opacity-50"
        >
          {uploading ? 'Uploading...' : 'Upload Logo'}
        </button>
        <input
          ref={fileRef}
          type="file"
          accept="image/png,image/jpeg,image/webp"
          onChange={(e) => {
            const file = e.target.files?.[0]
            if (file) handleLogoUpload(file)
          }}
          className="hidden"
        />
        <p className="text-xs text-cream/30 mt-1">Optional. Appears in printed reports.</p>
      </div>

      {/* Report Title */}
      <div>
        <label className="block text-sm text-cream/70 mb-2">Report Title</label>
        <input
          type="text"
          value={settings.reportTitle}
          onChange={(e) => setSettings((prev) => ({ ...prev, reportTitle: e.target.value.slice(0, 100) }))}
          maxLength={100}
          className="w-full bg-basalt border border-cream/20 rounded-lg px-3 py-2.5 text-sm text-cream focus:outline-none focus:border-sandstone/50"
        />
        <p className="text-xs text-cream/30 mt-1">{settings.reportTitle.length}/100</p>
      </div>

      {/* Footer Text */}
      <div>
        <label className="block text-sm text-cream/70 mb-2">Report Footer</label>
        <textarea
          value={settings.footerText}
          onChange={(e) => setSettings((prev) => ({ ...prev, footerText: e.target.value.slice(0, 200) }))}
          maxLength={200}
          rows={2}
          className="w-full bg-basalt border border-cream/20 rounded-lg px-3 py-2.5 text-sm text-cream focus:outline-none focus:border-sandstone/50 resize-none"
        />
        <p className="text-xs text-cream/30 mt-1">{settings.footerText.length}/200</p>
      </div>

      {/* Hide Notes Failsafe */}
      <div className="bg-basalt-50 rounded-card p-5">
        <div className="flex items-start gap-3">
          <input
            type="checkbox"
            checked={settings.hideNotesInPublicShare}
            onChange={(e) => setSettings((prev) => ({ ...prev, hideNotesInPublicShare: e.target.checked }))}
            className="mt-0.5 accent-sandstone"
          />
          <div>
            <p className="text-sm text-cream font-medium">Force-hide notes in public shares</p>
            <p className="text-xs text-cream/50 mt-1">
              When enabled, notes will be stripped from all public share links
              regardless of what users chose when creating them. This is a
              safety failsafe.
            </p>
          </div>
        </div>
      </div>

      {/* Save */}
      <div className="flex items-center gap-3">
        <button
          type="button"
          onClick={handleSave}
          disabled={saving}
          className="px-6 py-2.5 bg-sandstone text-basalt font-medium rounded-lg hover:bg-sandstone-light transition-colors disabled:opacity-50"
        >
          {saving ? 'Saving...' : 'Save Settings'}
        </button>
        {saved && (
          <span className="text-sm text-emerald-400">Saved!</span>
        )}
      </div>
    </div>
  )
}
